"""Generate unique wireframe edges from the pinned MediaPipe source, without importing it."""
import ast
from pathlib import Path

root = Path(__file__).resolve().parent.parent
source = root / '.deps/mediapipe-0.10.32/mediapipe/tasks/python/vision/face_landmarker.py'
tree = ast.parse(source.read_text(encoding='utf-8'))
edges = None
for node in ast.walk(tree):
    if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
        if node.target.id == 'FACE_LANDMARKS_TESSELATION':
            edges = sorted({tuple(sorted(ast.literal_eval(a) for a in c.args)) for c in node.value.elts})
assert edges and all(0 <= a < b < 468 for a, b in edges)
header = '''// Copyright 2023 The MediaPipe Authors.
// SPDX-License-Identifier: Apache-2.0
// Derived from MediaPipe v0.10.32 FaceLandmarksConnections (unique undirected edges).
// Generated by scripts/generate-topology.py. See THIRD_PARTY.md and data/licenses.
#pragma once
#include <array>
#include <utility>
namespace cam {
'''
header += f'inline constexpr std::array<std::pair<int, int>, {len(edges)}> mesh_edges = {{{{\n'
for start in range(0, len(edges), 8):
    header += '    ' + ', '.join(f'{{{a},{b}}}' for a, b in edges[start:start+8]) + ',\n'
header += '}};\n} // namespace cam\n'
(root / 'src/mesh-topology.hpp').write_text(header, encoding='utf-8')
print(f'Generated {len(edges)} unique mesh edges')
